fukamachi/qlot

src/util.lisp
This helps prevent outside systems from leaking in through the non-local quicklisp local-projects. It also opens up some interesting possibilities to allow git repos to be checked out directly to the local quicklisp's local-projects folder if someone wants to hack on them.
=> Rebind local-project-directories when using local quicklisp.

qlot-install.asd, src/shell.lisp
external-program uses /usr/bin/env to run external commands, which is obviously problematic on Windows. UIOP's RUN-PROGRAM is more portable, and looks like it does everything you need. I've tested this with a project of my own, and it was able to pull down all the various parts and QLOT:QUICKLOAD successfully.
=> Replace external-program with UIOP for windows compatibility.

src/parser.lisp, t/parser.lisp
For me it's more natural to use `;;` comments in the qlfile.
The old `#` comment still works.
=> Support lispy ; comment in qlfile

src/shell.lisp
When cloning via ssh, the ssh process that git starts needs to
prompt for a password, which requires a terminal or an ssh-askpass
program. When the input is not a terminal (the default) but ssh is
being run in a terminal session, ssh detects the following:
1) stdin is not a terminal, so we can't prompt there, but
2) there /is/ a controlling terminal for the process, so we
shouldn't use ssh-askpass to produce a graphical prompt.
This causes ssh to hang, and makes ssh-based git sources unusable
when running e.g. QLOT:INSTALL from an actual terminal. Using
:INPUT :INTERACTIVE allows ssh to use the terminal in terminal
sessions, and to use ssh-askpass when run from a non-terminal
(e.g. emacs).
Steps to reproduce the original issue:
1. Create a qlfile for an ssh git source, with an ssh-key …
=> Allow git to inherit the lisp's stdin for terminal detection.

src/source.lisp
`UIOP:DIRECTORY-FILES` returns normalized pathnames,
but the source directory might have non-normal
components like '.' in it. If `ASDF:*CENTRAL-REGISTRY*`
contains a path like `#P"/foo/./"`, `DIRECTORY-FILES`
will return paths like `#P"/foo/bar.txt"`. Since the
length of the directory component differs, `SUBSEQ`
will wind up chopping characters off of the file
name, which causes all sorts of inscrutable errors
later.
=> Normalize source path to compute system file paths.

src/install.lisp
This PR fixes issues with read-only files on Windows under SBCL. #28 fixed the problem for CCL, but SBCL (and maybe others) have the same issue, so I've changed the feature check to just `#+windows`, since it shouldn't hurt lisps that don't strictly need it.
This branch also fixes an issue in the `attrib` call where `uiop:subpathname` was producing a non-wild pathname who namestring was the mangled `"^*.^*"` instead of `"*.*"` like you'd expect. I did it by converting the directory to a namestring and tacking on the wildcard with `format`, but if you weren't comfortable with that, there are other options:
1. Add an extra `#\\` character before the wildcard just in case -- we know this is windows, so we don't have to worry about which path separator to use.
2. Make wild pathname with …
=> Read only attrib

qlot-install.asd, src/install.lisp, src/proxy.lisp, src/source/github.lisp, src/source/http.lisp, src/source/ql.lisp
Depend on https://github.com/fukamachi/dexador/pull/26
I think if qlot runs on proxy environment, it makes us more happy.
When set "http_proxy" or "HTTP_PROXY", This PR use it.
=> Add capability to survive under proxy environment

util.lisp
Pathnames contain more components than just the directory, name, and type;
if you create a directory pathname out of a name, type, and directory,
you'll lose the other parts of the original pathname. By using :defaults,
you can un-set specific components and inherit the rest from the original
pathname.
This fixes qlot:quickload on Windows, which stores the drive letter of
paths in the DEVICE component of pathnames.
=> Preserve pathname components when getting a directory pathname.

util.lisp
In asdf 3.3 `asdf::*defined-systems*` was replaced with
`asdf::*registered-systems*`, which also changed the structure of the data:
the values in that hashtable are the system objects, and not a cons of the
timestamp and the system object. This adapts the code to handle both cases,
so it should remain compatible with older asdf releases.
=> Fix handling of asdf::*registered-systems* values in asdf 3.3.

.travis.yml, dist.lisp, install.lisp, parser.lisp, source.lisp, source/git.lisp, source/github.lisp, source/http.lisp, source/ql.lisp, util.lisp
This pull request adds ability to define and use custom Quicklisp distributions, as suggested in https://github.com/fukamachi/qlot/issues/58:
```
dist ultralisp http://dist.ultralisp.org/
ql :all :latest
ultralisp weblocks 20180827-194049
github slynk joaotavora/sly
…
```
I think code should be refactored a little bit before this pull can be merged.
=> Added a 'dist' command to use custom Quicklisp distributions

README.markdown, qlot.asd, roswell/qlot.ros, tests/util.lisp, util.lisp
This useful, to add a directory, containing a libraries, available only locally.
For example, I have some libraries at my `~/common-lisp/` directory. But when I make "isolated" environment using Qlot, quicklisp does not see them even if I run qlot like that:
```
CL_SOURCE_REGISTRY=~/common-lisp// qlot exec ros emacs
```
This patch fixes this behavior and if environment variable `CL_SOURCE_REGISTRY` is already defined, then Qlot uses it's content and extends it, making all libraries from `~/common-lisp/` directory (or other) available.
=> Now qlot exec extends value of CL_SOURCE_REGISTRY env variable if it is exists.

util.lisp
`The variable QLOT/UTIL::*ALREADY-SEEN* is unbound.` may be occur in `all-required-systems` because `*already-seen*` is unbound.
I initialized `*already-seen*` as `nil`.
=> initialize qlot/util::*already-seen* as nil

roswell/qlot.ros
`*default-directory-defaults*` shall be `*default-pathname-defaults*`.
=> Fixed typo

install.lisp, main.lisp
This PR attempts to fix https://github.com/fukamachi/qlot/issues/74 by consistently using primary-system-name with ql-dist:find-system
=> Resolve primary system name when installing dependencies

.travis.yml, archive.lisp, install.lisp, parser.lisp, server.lisp, source/git.lisp, source/http.lisp, source/ql.lisp, util.lisp
This PR removes the following dependencies.
* alexandria
* cl-ppcre
* split-sequence
* archive
* salza2
* gzip-stream
Still ironclad is required for calculating a digest of files, and dexador & yason are required by http/github sources.
=> Reduce dependencies

README.markdown, install.lisp, main.lisp, parser.lisp, roswell/qlot.ros, tests/main.lisp, util.lisp
As Quicklisp searches the local-projects directory recursively, it also
searches inside project-local Quicklisp dists if there's a project which
uses Qlot.
I personally heard that @snmsts is willing to add a system searcher which ignores dot-started directories.
With this patch, the issue would be resolved.
=> Change the directory name of project-local Quicklisp to '.qlot/'.

source/ql.lisp
'ql' source cannot lock the version even when there's a qlfile.lock.
```
#qlfile
ql fast-http :latest
```
```
#qlfile.lock
("quicklisp" .
(:class qlot.source.ql:source-ql-all
:initargs (:project-name "quicklisp" :%version :latest)
:version "2018-02-28"))
("fast-http" .
(:class qlot.source.ql:source-ql
:initargs (:project-name "fast-http" :distribution "http://beta.quicklisp.org/dist/quicklisp.txt" :%version :latest)
:version "ql-2019-03-07"))
```
```
qlot install
ls .qlot/dists/fast-http/softwares
```
=> Fix the bug that 'ql' source ignores the version of the project lock.

roswell/qlot.ros
Here's the first few lines of it:
```
$ qlot exec qlot exec ros run
Unhandled ASDF/FIND-COMPONENT:MISSING-COMPONENT in thread #<SB-THREAD:THREAD "main thread" RUNNING
{10005505B3}>:
Component #:QLOT/CLI not found
```
- Qlot v0.10.0
=> Fix a MISSING-COMPONENT error when executing 'qlot exec' recursively.

utils.lisp
The old package name is refered by some libraries.
Fix https://github.com/inaimathi/cl-notebook/issues/71.
fixes #95
=> Add QLOT/UTIL nickname to QLOT/UTILS.

cli.lisp, install.lisp, roswell/qlot.ros
This option turns off dependencies installation. In some cases, this can be useful. For example, `qlot install` may fail if some of the lisp files reference a missing package.
I already made attempt to fix such issue (https://github.com/fukamachi/qlot/pull/73) but @fukamachi said it should be fixed in 0.10.x version of Qlot. Now I see, there is still the possibility to encounter such an issue in some cases.
Here is a minimal setup to reproduce this issue:
```
mkdir test-qlot
cd test-qlot
echo '' > qlfile
echo '(defsystem "test" :class :package-inferred-system)' > test.asd
echo '(cl-fad:list-directory "")' > some.lisp
qlot install
```
This will produce the following error:
```
Unhandled SB-INT:SIMPLE-READER-PACKAGE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
{10004F84C3}>: …
```
=> Added an option "--no-deps".

install.lisp, utils/asdf.lisp
This is found when installing a system whose ASD file depends on cl-debug-print (not in Quicklisp yet).
=> Allow to load libraries having defsystem dependencies which don't in Quicklisp

utils/asdf.lisp
`$ qlot install` をしたときにそのディレクトリ以下にread errorが起こるlispファイルがあると途中で中断してしまう問題があり、それを回避するようにしました。
=> avoid read error in 'qlot install'

install.lisp
Dist installation creates case sensitive path / folder for dist. But (ql-dist:dist string) method downcases string before lookup. That causes the following error:
```
Already have dist "Shinmera-plump" version "ultralisp-20200615113009".
Unhandled SB-PCL::NO-APPLICABLE-METHOD-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
{10012E0613}>:
There is no applicable method for the generic function
#<STANDARD-GENERIC-FUNCTION QL-DIST:BASE-DIRECTORY (3)>
when called with arguments
(NIL).
See also:
The ANSI Standard, Section 7.6.6
```
This breaks some Ultralisp dependencies.
Using FIND-DIST as it is not doing string downcase to dist name.
=> Fix handling of projects with names containing uppercase letters

proxy.lisp
This commit closes issue https://github.com/fukamachi/qlot/issues/104
For some reason, code loaded from the fasl file, wrapper code
called a dummy function ORIG-HTTP-FETCH instead of
a real original function saved to the symbol function.
I don't really understand the reason this strange bug, but
separating a wrapper definition helped to solve this problem.
Tested on SBCL 2.1.2 under OSX.
=> Fixed the issue when Qlot failed to download Quicklisp installer.

distify/dist.lisp
This also requies a fixed Quicklisp client with
changes from this pull-request:
https://github.com/quicklisp/quicklisp-client/pull/206
Here is example qlfile where the custom distribution with
forked libs takes precedence over Ultralisp and Quicklisp:
dist ultralisp http://dist.ultralisp.org/
dist svetlyak40wt/my-forks http://dist.ultralisp.org/svetlyak40wt/my-forks.txt
=> Allow using custom dists which names where name contains /

README.markdown, bundle.lisp, cli.lisp, distify/git.lisp, install.lisp, main.lisp, utils/project.lisp, utils/ql.lisp
`qlot bundle` dumps all project dependencies into '.bundle-libs/' and makes them available without Qlot and Quicklisp.
This feature is achieved with `ql:bundle-systems`.
See https://www.quicklisp.org/beta/bundles.html for the detail.
=> Add 'bundle' subcommand

README.markdown, source/github.lisp, tests/data/qlfile5, tests/distify/github.lisp
```
github datafly fukamachi/datafly
```
```
github fukamachi/datafly
```
This keeps backward-compatibility.
=> Change the definition of 'github' source.

scripts/run.sh
Before the change, the following error occurred.
```
$ qlot exec
/home/user/.qlot/qlot/scripts/run.sh: line 19: exec: exec: not found
```
=> Fix for `qlot exec ...` command

scripts/setup.sh
Some users' settings will print the directory that `cd` changes into, so
we redirect all output unconditionally to /dev/null.
=> setup: suppress output from cd

utils/asdf.lisp
It may raise a read error when looking for defpackage form of non package files.
=> Prevent errors when collecting dependencies of package-inferred-system.

README.markdown, fetch.lisp, local-init/https.lisp, scripts/fetch.sh, scripts/qlot-installer.sh, scripts/run.sh, scripts/setup.sh, utils/http.lisp
Qlot downloads files via HTTPS when running `qlot install`. However, when using a project-local Quicklisp without Qlot, the general ql-http is used and download files via HTTP.
This PR adds `local-init/https.lisp` to fetch archives and metadata files via HTTPS without loading Qlot in the main process. This also used to download dependencies of Qlot when running setup.
=> Use HTTPS when running ql:quickload

src/utils/project.lisp
It may raise an error if there's the same system in user-wide.
=> Fix project-dependencies not to load ASD files to detect if it's a package-inferred-system

install.lisp
When you are using a distribution name different from the name in it's metadata, qlot returned this error:
```
Unhandled SB-PCL::NO-APPLICABLE-METHOD-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
{10004F84C3}>:
There is no applicable method for the generic function
#<STANDARD-GENERIC-FUNCTION QL-DIST:BASE-DIRECTORY (3)>
when called with arguments
(NIL).
See also:
The ANSI Standard, Section 7.6.6
Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10004F84C3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SB-PCL::NO-APPLICABLE-METHOD-ERROR {1004D471A3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<SB-PCL::NO-APPLICABLE-METHOD-ERROR {1004D471A3}>)
2: (INVOKE-DEBUGGER #<SB-PCL::NO-APPLICABLE-METHOD-ERROR {1004D471A3}>)
3: (ERROR …
```
=> Output more info instead SB-PCL::NO-APPLICABLE-METHOD-ERROR when using custom quickdist source with wrong name

.github/workflows/ci.yaml, local-init/qlot-10-https.lisp, qlot.asd, scripts/run.sh, src/check.lisp, src/cli.lisp, src/distify.lisp, src/distify/dist.lisp, src/distify/git.lisp, src/distify/github.lisp, src/distify/http.lisp, src/distify/ql.lisp, src/fetch.lisp, src/install.lisp, src/logger.lisp, src/progress.lisp, src/secure-downloader.lisp, src/server.lisp, src/utils/dependencies.lisp, src/utils/project.lisp
Run libraries' dist installation in parallel while in `qlot install` or `qlot update`.
The number of threads can be specified with `--jobs` option. (Default: 4)
=> Parallel installation

src/utils/archive.lisp
sometimes qlot hangs on some github archives with the status `Extracting a tarball.`  This is caused by an incomplete tarball file.
=> fix 'extract-tarball': flush tar-stream buffer before extract

local-init/qlot-99-setup.lisp, src/utils/qlot.lisp
Adds `.bundle-libs` and `.direnv` to a list of exclusions to look for ASD files.
Rerunning of `qlot install` at each project root is required to apply these changes.
ref #232
=> Ignore ".direnv" to look for ASD files in a project.

src/install.lisp, src/progress.lisp, src/utils.lisp
The metadata files can be different if the line in releases.txt or systems.txt is longer than 1024.
=> Fix metadata files for `ql` or `ultralisp`

local-init/qlot-99-setup.lisp
This will remedy a problem that was taking a long time when loading systems. Happens since v1.5.0.
ref #233
=> Optimize project-searcher by not running unnecessarily.

.github/workflows/ci-exec.yaml, local-init/qlot-99-setup.lisp
Fixes #250.
Upgrading is not enough to fix it. Rerun `qlot install` to update scripts in `.qlot/local-init`.
=> Fix local-init script to work on ECL (ASDF 3.1).

src/distify/github.lisp, src/http.lisp
It could fail when there are more than 30 branches. (Fix #252)
=> Fix an error while retrieving the git ref for `github` sources.

src/cli.lisp
Something I noticed while using `qlot`.
=> tweak: minor grammar correction

src/utils/qlot.lisp
=> Warn if the directory being added as 'local' source does not exist.

src/utils/quickdocs.lisp
```
$ qlot add dbi --upstream
qlot: 'dbi' is not found.
```
It should be `cl-dbi`.
=> Show a specific error when trying to install an unknown library.

src/source/github.lisp, tests/install.lisp
=> Fix `qlot update` to allow to take `github`'s project names for update.

.gitattributes, local-init/qlot-10-https.lisp, src/utils/cli.lisp
* Ensure the `which` function works on Windows
* Add a `gitattributes` file to ensure that when `ros install fukamachi/qlot` is run on Windows, the lisp files are NOT checked out with Windows line endings, as the carriage returns choke up SBCL
* Ensure that stdin and stdout are properly inherited on Windows so that the REPL doesn't just immediately exit when running `rsc qlot exec ros run`
The `rsc` command above is simply a batch file on the windows path, with this in it:
```
@echo off
ros -Q -L sbcl-bin -- "C:\Users\<USERNAME>\.roswell\lisp\quicklisp\bin\%*"
```
=> Make Windows-related changes

src/progress.lisp
When parallel processing is enabled on Windows, reading the tarball to obtain an md5 hash when writing out the releases.txt file in the file `src/utils/distify.lisp` seems to segfault. Disabling processing on Windows solves the problem. Related to #289 .
Thanks!
=> Disable parallel processing on windows to fix #289

roswell/qlot.bat
Right now, I can't just run `qlot install` on Windows from a CMD prompt. In order to do so, I have to have this script, named `rsc.bat`, on my PATH:
```batch
@echo off
ros -Q -L sbcl-bin -- C:\Users\bhw\.roswell\lisp\quicklisp\bin\%*
```
And run `rsc qlot install` instead.
This PR fixes this. By having a `.bat` file in the `roswell` directory, it gets installed into roswell's `bin/` folder, which is on the windows PATH. It finds itself in the file system, and runs the roswell script that is next to it within the same directory.
By adding this file, I can now just `ros install fukamachi/qlot` on Windows, followed by `qlot install` in my project directory, and it works.
=> Add ability to run from powershell or CMD prompt on Windows

src/check.lisp
=> Fix an unexpected error in `qlot outdated` due to missing a symbol import.

src/source/github.lisp, tests/data/qlfile5.lock, tests/install.lisp
Currently, it always uses the latest version of the branch.
=> Fix `github` projects to use the version specified in qlfile.lock.

README.markdown, src/check.lisp, src/cli.lisp, src/install.lisp, src/source.lisp, src/source/asdf.lisp, src/utils/git.lisp
**Experimental feature**
Add a new source `asdf` to use a newer version of ASDF by downloading the source code to `.qlot/local-projects`.
ref #245
```
asdf 3.3.7.1
```
```
$ qlot add asdf 3.3.7.1
```
* Only newer ASDF than the bundled one is permitted.
=> Add `asdf` source to use a newer ASDF.

src/distify/git.lisp, src/distify/github.lisp, src/source/base.lisp, src/utils/distify.lisp, src/utils/git.lisp, tests/distify/git.lisp, tests/distify/github.lisp
This will make it possible to provide date-based information in results. (ex. in `qlot outdated`)
=> Add `qlot.published-date` to distinfo.txt for `git` & `github` sources.

README.markdown
Fixed the README documentation, in particular on the Vim/Neovim part regarding Vlime setup. The parameter to the `--eval` flag was not properly prefixed as parameters should be in vimscript.
Further, I updated the README to include a setup option using Vlime for those not using Roswell as a starting point. This caused issues in my own local setup. The alternative I added shows the example of using SBCL, but I am as of yet unsure how it would look like using other implementations. I believe it to be fine, since most people use SBCL, and so the chances of it being spot-on are higher than, well, not having anything of the sort.
See #313.
=> Update README to fix issues and include option for people using Vim but not Roswell
