- src/util.lisp
Not sure how you feel about this, but it seems like ASDF should always have knowledge of the actual systems that are loaded, even if they're in the local Quicklisp.
More background on where I'm coming from with this: I love this project (I was going to start hacking my own solution to this until I saw it in the Quicklisp update announcement). I have a number of projects that use things like ASDF:SYSTEM-RELATIVE-PATHNAME to find other (non-lisp) files and this patch restores that functionality.
After leaving the local Quicklisp environment, update ASDF::*DEFINED-SYSTEMS* to include the systems that were loaded from the local environment. This keeps ASDF up to date with the systems that are actually loaded and allows things like FIND-SYSTEM and SYSTEM-RELATIVE-PATH-NAME to work as expected …
> Update ASDF::*DEFINED-SYSTEMS* after leaving local Quicklisp.

- roswell/qlot.ros
- src/qlot.lisp
It bundles dependencies into `bundle-libs/` by `ql:bundle-systems`.
> Add qlot:bundle

- circle.yml
- src/archive.lisp
- src/parser.lisp
- src/shell.lisp
- src/source.lisp
- src/source/git.lisp
- src/source/ql.lisp
- src/tmp.lisp
- t/data/qlfile-crlf
- t/parser.lisp
> Prevent autocrlf for 'git' projects

- src/install.lisp
> Fix Windows CCL can't install libraries from git source

- source.lisp
> Fixed error on dependencies like (:REQUIRE :EXTENSIBLE-SEQUENCES).

- install.lisp
- source/ql.lisp
- util.lisp
Just ensuring dependencies installed. (ref #63)
> Don't actually load project systems when 'qlot install'

- source/ql.lisp
> Fix the error when distinfo-template-url isn't in distinfo.txt

- util.lisp
> Leave the old definition of 'with-retrying' for ASDF v3.2.

- utils/shell.lisp
> Don't refer QL package in utils/shell.

- install.lisp
> Add sb-posix as a dependency to qlot/install

- README.markdown
- cli.lisp
- tests/Dockerfile
> Add 'qlot add' command

- qlot.asd
- source/git.lisp
- tests/check-dependencies-script.lisp
- tests/main.lisp
- utils.lisp
Add a test to ensure that the Qlot core is dependency free.
> Omit the dependency on QURI in qlot/source/git.

- cli.lisp
> Revert qlfile on error after 'qlot add'.

- server.lisp
- utils/shell.lisp
> Fix an unhandled error for unknown libraries in a dist.

- README.markdown
- scripts/qlot-installer.sh
```
curl https://raw.githubusercontent.com/fukamachi/qlot/master/scripts/qlot-installer.sh | bash
```
> Add an automatic Qlot installer.

- README.markdown
- cli.lisp
- errors.lisp
- install.lisp
By this change, --project option will be deprecated.
> Change 'qlot update' allow to take names of dependencies to update.

- README.markdown
This Pull Request fixes a typographical error in the README.md file.
Corrected "usefull" to "useful" in the README.md file.
This fix is not related to any existing issue. It's a minor typo that I noticed while reviewing the README.
Thank you for considering this contribution.
> Remove typo

- bundle.lisp
- cli.lisp
- utils.lisp
- utils/asdf.lisp
- utils/project.lisp
```
$ qlot bundle --exclude myapp/tests --exclude myapp/tests/*
```
> Add a new option `--exclude` to `qlot bundle`

- README.markdown
This Pull Request fixes a grammatical error in the README.md file.
Fixed grammatical errors in README.markdown
This fix is not related to any existing issue. It's a minor typo that I noticed while reviewing the README.
Thank you for considering this contribution.
> Fixed grammatical errors in README.markdown

- cli.lisp
- errors.lisp
- install.lisp
- parser.lisp
It checks if qlfile.lock and the project-local Quicklisp are up-to-date.
> Add 'check' subcommand.

- src/cli.lisp
- src/utils/cli.lisp
```
$ qlot exec sbcl
$ qlot exec ros run
$ qlot exec alisp
$ qlot exec ccl
$ qlot exec clisp
$ qlot exec abcl
$ qlot exec ecl
```
> Allow to run 'qlot exec' with other Lisps.

- .github/workflows/ci.yaml
- README.markdown
- scripts/install.sh
- scripts/qlot-installer.sh
- scripts/qlot-uninstaller.sh
- scripts/setup.sh
- src/main.lisp
* Add scripts/install.sh
* Allow to place qlot.asd on system registry for all users
> Add scripts/install.sh for manual installation

- src/bundle.lisp
- src/utils/asdf.lisp
It's found in lem-project, which has a dependency on 'lem-mailbox', and it depends on 'lem'.
> Ignore the project systems for bundling.

- src/install/quicklisp.lisp
* Don't delete the directory, delete Qlot's files instead
* Always install even when the Qlot's version is the same
> Change the condition to install local-init files.

- src/utils/asdf.lisp
- src/utils/project.lisp
> Eval forms in asd files while determining project dependencies.

- .github/workflows/build-image.yaml
- .github/workflows/release.yaml
- Dockerfile
And ensure to use the same version of Ultralisp.
> Run tests before building Docker images for releases

- src/distify/git.lisp
- src/distify/github.lisp
- src/distify/http.lisp
- src/distify/ql.lisp
- src/errors.lisp
- src/http.lisp
- src/source/base.lisp
- src/source/dist.lisp
- src/source/git.lisp
- src/source/github.lisp
- src/source/http.lisp
- src/source/local.lisp
- src/source/ql.lisp
- src/source/ultralisp.lisp
- tests/parser.lisp
> Raise `invalid-project-name` error when a project name contains `/`.

- src/main.lisp
- src/utils/repl.lisp
> Add `with-local-quicklisp` again.

- src/http.lisp
> Make HTTP timeout longer and retry on socket errors.

- src/http.lisp
> Retry also on `sb-bsd-sockets:interrupted-error`.

- src/http.lisp
> Retry also on `usocket:timeout-error`.

- src/utils/git.lisp
> Fix an error during `git clone` for repositories which don't support `--depth` option.

- src/utils/git.lisp
This is a follow-up fix. The error happens if the git repository doesn't support shallow clone and `:ref` is specified.
ref. https://github.com/fukamachi/qlot/issues/286#issuecomment-2388638231
> Fix an error from `git fetch` command trying to unshallow for a full repository.

- src/distify/ql.lisp
This may cause differences in qlfile.lock.
> Fix the version of `ql` sources not to be updated by `qlot install` if it's locked.

- src/utils/distify.lisp
> Fix the distinfo URL for custom dists that have a different file name for distinfo.txt.

- src/install.lisp
> Fix not to update dists whose versions are fixed in qlfile.
